name: Daily Script

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Adjust this as needed

      - name: Install dependencies
        run: |
          pip install -r /workspaces/BlizzardX/requirements.txt

      - name: Run script
        run: |
          python /workspaces/BlizzardX/Scripts/Weather_data_pipline.py
